monblog_home:
    path: /
    controller: App\Controller\HomeController::main

monblog_page:
    path: /show/{page}
    controller: App\Controller\HomeController::indexByPage
    defaults:
        page: 1
    requirements:
        page: \d+

monblog_letter:
    path: /show/{letter}
    controller: App\Controller\HomeController::indexByLetter
    requirements:
        letter: \w
#---------------------------
#------- Author -----------#
#---------------------------

monblog_author_showAll:
    path: /author
    controller: App\Controller\AuthorController::showAll

monblog_author_show:
    path: /author/{id}
    controller: App\Controller\AuthorController::show
    requirements:
        id: \d+


monblog_author_create:
    path: /author/create
    controller: App\Controller\AuthorController::create

monblog_author_update:
    path: /author/update/{id}
    controller: App\Controller\AuthorController::update
    requirements:
        id: \d+

monblog_author_delete:
    path: /author/delete/{id}
    controller: App\Controller\AuthorController::deleteAjax
    requirements:
        id: \d+

#---------------------------
#------- Article -----------#
#---------------------------

monblog_article_showAll:
    path: /article
    controller: App\Controller\ArticleController::showAll

monblog_article_show:
    path: /article/{id}
    controller: App\Controller\ArticleController::show
    requirements:
        id: \d+


monblog_article_create:
    path: /article/create
    controller: App\Controller\ArticleController::create

monblog_article_update:
    path: /article/update/{id}
    controller: App\Controller\ArticleController::update
    requirements:
        id: \d+

#monblog_article_delete:
#    path: /article/delete/{id}
#    controller: App\Controller\ArticleController::delete
#    requirements:
#        id: \d+

monblog_article_delete:
    path: /article/delete/{id}
    controller: App\Controller\ArticleController::deleteAjax
    requirements:
        id: \d+


#---------------------------
#------- Tags -----------#
#---------------------------

monblog_category_showAll:
    path: /category
    controller: App\Controller\CategoryController::showAll

monblog_category_update:
    path: /category/update/{id}
    controller: App\Controller\CategoryController::update
    requirements:
        id: \d+

monblog_category_delete:
    path: /category/delete/{id}
    controller: App\Controller\CategoryController::deleteAjax
    requirements:
        id: \d+



#---------------------------
#------- Credit -----------#
#---------------------------

monblog_credit:
    path : /credit
    controller: App\Controller\PaymentController::creditAccount



#---------------------------
#------- Test -----------#
#---------------------------
monblog_test:
    path: /test
    controller: App\Controller\HomeController::TestMercure


monblog_chat:
    path: /chat
    controller: App\Controller\HomeController::getChatAjax


#---------------------------
#------- Static page ------#
#---------------------------

monblog_cgv:
    path: /cgv
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController\
    defaults:
        template: staticPages/cgv.html.twig